### ISSUE TITLE
did not work with phasmophobia

### ISSUE THREAD

**Issue by Jamesdabeast** [ItsKaitlyn03/OculusKiller#15]
Tried playing phasmophobia and was stuck on a black screen. tried it a few times then reverted back to the original .exe and worked fine.

**Comment by ItsKaitlyn03** [comment]
you need to launch steamvr first via launching oculusdash, aka plug your headset in and load into steamvr

**Comment by Jamesdabeast** [comment]
I did launch it from inside steamvr, but ill try again today.

**Comment by UnusualNorm** [comment]
@Jamesdabeast If you are still experiencing this problem, did you set your default OpenXR runtime to SteamVR?

**Comment by Jamesdabeast** [comment]
@UnusualNorm yes, im not sure how to change the runtime, but Vrchat and Pavlov work fine.

**Comment by UnusualNorm** [comment]
@Jamesdabeast You can find the settings by showing advanced settings, then under the "developer" tab you find "Current OpenXR Runtime"
You might want to just double check.
![image](https://user-images.githubusercontent.com/40722525/167042034-8b2cc7a8-fff9-490a-8b37-61a152f56ed1.png)

**Comment by Jamesdabeast** [comment]
@UnusualNorm Thank you, that worked!
