### ISSUE TITLE
Discord Community?

### ISSUE THREAD

**Issue by UnusualNorm** [ItsKaitlyn03/OculusKiller#21]
Hey there! I was wondering if there was a Discord server people could join to get news and talk about development?

**Comment by ItsKaitlyn03** [comment]
Hrm, now that I think about it. I'll make one soon, thanks for the suggestion :P

**Comment by ItsKaitlyn03** [comment]
UPDATE: I have created a Discord server https://discord.gg/dPsfJhsGwb
