### ISSUE TITLE
Steamvr not booting despite having it installed and booted

### ISSUE THREAD

**Issue by Bakupham** [ItsKaitlyn03/OculusKiller#26]
I believe I have the oculuskiller installed correctly, and yet I get this error
![image](https://user-images.githubusercontent.com/55063194/167273940-eb4d3b60-1f06-4bff-b5ff-c7236ace8978.png)

**Comment by huliqan** [comment]
Yes! it appear in home v.40.82 but works fine in previous versions (38 works fine)
Please give new release of  OculusKiller !!!

**Comment by huliqan** [comment]
check this file!
C:\Users\XXX\AppData\Local\openvr\openvrpaths.vrpath

**Comment by Bakupham** [comment]
```
{
	"config" : 
	[
		"C:\\Program Files (x86)\\Steam\\config"
	],
	"external_drivers" : 
	[
		"D:\\Games\\SteamLibrary\\steamapps\\common\\LIV\\resources\\LIV Virtual Camera\\00liv_virtualcamera",
		"D:\\owo-track-release\\driver"
	],
	"jsonid" : "vrpathreg",
	"log" : 
	[
		"C:\\Program Files (x86)\\Steam\\logs"
	],
	"runtime" : 
	[
		"A:\\SteamLibrary\\steamapps\\common\\SteamVR",
		"C:\\Program Files (x86)\\Steam\\steamapps\\common\\SteamVR",
		"c:\\program files (x86)\\steam\\steamapps\\common\\SteamVR"
	],
	"version" : 1
}
```

That's what it says

**Comment by huliqan** [comment]
try to delete
"C:\\Program Files (x86)\\Steam\\steamapps\\common\\SteamVR",
or
	[
		"D:\\Games\\SteamLibrary\\steamapps\\common\\LIV\\resources\\LIV Virtual Camera\\00liv_virtualcamera",
		"D:\\owo-track-release\\driver"
or whole file 
C:\Users\XXX\AppData\Local\openvr\openvrpaths.vrpath
and launch
...\Steam\steamapps\common\SteamVR\bin\win64\vrmonitor.exe

**Comment by Bakupham** [comment]
I did what you said about deleting the thing then booting vrmonitor, then I tried using oculus killer again and I got the same error this is now what the vrpath file says now
```
{
	"config" : 
	[
		"c:\\program files (x86)\\steam\\config"
	],
	"external_drivers" : null,
	"jsonid" : "vrpathreg",
	"log" : 
	[
		"c:\\program files (x86)\\steam\\logs"
	],
	"runtime" : 
	[
		"A:\\SteamLibrary\\steamapps\\common\\SteamVR"
	],
	"version" : 1
}
```

**Comment by Bakupham** [comment]
@UnusualNorm thanks for the info! If I may ask, is there an eta. on when the update will be release?

**Comment by UnusualNorm** [comment]
@Bakupham Good news! I found a workaround to fix my Visual Studio, and also found an easy way to find the SteamVR path! You can find the fix in PR #30!

**Comment by Bakupham** [comment]
oh interesting! I might take a look! though I'm not too familiar with github. will I be able to grab it from the same place I grabbed the original release?

**Comment by UnusualNorm** [comment]
Let me make a build rq

**Comment by UnusualNorm** [comment]
https://github.com/UnusualNorm/OculusKiller/releases/tag/ExternalSteamVRFix Should be the correct binary

**Comment by UnusualNorm** [comment]
@Bakupham Did this fix your issue?

**Comment by Bakupham** [comment]
oh I'll try it right now

**Comment by Bakupham** [comment]
![image](https://user-images.githubusercontent.com/55063194/167528136-c57ff6fb-4067-467f-841b-a770ce46965d.png)
failure sadly

**Comment by huliqan** [comment]
> "A:\\SteamLibrary\\steamapps\\common\\SteamVR"

is it realy path?
Works now?

**Comment by UnusualNorm** [comment]
Hmm, I'll look into this.

**Comment by Bakupham** [comment]
hmm... that new version release of OK didn't seem to fix it either... 
![image](https://user-images.githubusercontent.com/55063194/168489169-cae8bbfc-0065-4e4a-81c8-db0071c18d8d.png)

**Comment by huliqan** [comment]
new version 1.1.0 dos't work in my home
1.0.0 works very fine!

**Comment by UnusualNorm** [comment]
@Bakupham Sorry OculusKiller was unable to find your SteamVR location. But here is a copy-paste from our Discord for a workaround:

---
You can manually override where windows thinks SteamVR is (and thus, OculusKiller) by opening "regedit.msc" and navigating to this location: "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 250820" then changing the "InstallLocation" property to where your SteamVR base directory is located.

**Comment by Bakupham** [comment]
hmm seems windows is targeting where steamvr used to be. Here's a possible fix, perhaps if steamvr fails to load perhaps in the error box you can give the user an option to manually target vrmonitor. Though maybe I just don't know how the program works and maybe it has to work this way, but hey if the fix works then it works, ya know? anyways I'm gonna try the manual override and then test to see if OK works

![image](https://user-images.githubusercontent.com/55063194/168661420-0cfb37a3-6a05-4868-a920-ba98fcd367ef.png)

**Comment by Bakupham** [comment]
I THINK IT WORKED! IM TYPING VIA STEAMVR ATM! With a lower spec machine i need all the boist to performanxe i can get so ow hopefully ill get some better performance

**Comment by UnusualNorm** [comment]
poggers

**Comment by huliqan** [comment]
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 250820

I have not this, I dos't installed steamVR(steam folder lays in another drive in my comp)
what should be there?  in ...\Uninstall\Steam App 250820
