### ISSUE TITLE
v.1.1.0 don't work

### ISSUE THREAD

**Issue by huliqan** [ItsKaitlyn03/OculusKiller#36]
v.1.0.0 works fine for me
v.1.1.0 don't work
(says "can't find StemVR" )
https://user-images.githubusercontent.com/55063194/167273940-eb4d3b60-1f06-4bff-b5ff-c7236ace8978.png
...................
win10x64 20H2 | i5-4670K 4.5GHz | 16Гб DDR3 | MSI GTX1080ti GAMING X 11G  | Oculus Quest2

**Comment by UnusualNorm** [comment]
Sorry v1.1.0 didn't work, please try out this experimental release and tell me if it fixes your issue: [v1.2.0](https://github.com/HyrumGG/OculusKiller/releases/tag/v1.2.0)

**Comment by huliqan** [comment]
many thanks! 
After writed in regedit uninstall-path steamVR for me works fine and 1.1.0 version of your progs!
now will testing 1.2.0 vers.

**Comment by huliqan** [comment]
1.2.0 works fine!
