### ISSUE TITLE
Keeps sayings couldn't find steamvr despite all fixes

### ISSUE THREAD

**Issue by FindingEDENxo** [ItsKaitlyn03/OculusKiller#37]
Keeps asking if installed and ran despite me having it done both. I have the Oculus app installed to my E: drive and same with steam if that effects anything
![image](https://user-images.githubusercontent.com/70388842/168667159-02e29be5-3102-4507-ba7e-876b60605fcf.png)

**Comment by UnusualNorm** [comment]
Sorry v1.1.0 didn't work, please try out this experimental release and tell me if it fixes your issue: [v1.2.0](https://github.com/HyrumGG/OculusKiller/releases/tag/v1.2.0)

**Comment by FindingEDENxo** [comment]
It seems to be fixed! It instantly booted up SteamVR with no problems at all. Unsure if this has to do with me also doing all the troubleshooting before hand but either way it worked for me now!
