### ISSUE TITLE
no way to exit oculus link.

### ISSUE THREAD

**Issue by JamerGamerNL** [ItsKaitlyn03/OculusKiller#4]
I love this program but the only problem is that there is no way to exit oculus link in vr. I don't know if it is possible to add such a feature, but I hope it is. I would suggest that you fold the oculus button for 5 soconds or something like that.

still though, great work.

**Comment by KillaNista** [comment]
You can exit Link/ Airlink mode by stopping OVRService in the Task Manager.

**Comment by JamerGamerNL** [comment]
I said in vr.

**Comment by KillaNista** [comment]
Yeah in VR. You can open the SteamVR menu via menu button, choose the desktop view there and stop the OVRService in the Task Manager.

**Comment by JamerGamerNL** [comment]
For some reason task manager doesn't work for me in vr. Probably because it is an administrative program

**Comment by KillaNista** [comment]
It shouldn't make any difference whether you use the task manager in VR. 
But try this instead. Create a txt file - insert:

"@echo off 
NET STOP OVRService
exit"

Rename the text file to "stop.bat" Now you can long click on it in VR desktop view, 
choose - run as administrator and the bat file will do the rest.
